# Generated by Django 5.0.1 on 2024-02-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='current_sy',
        ),
        migrations.AddField(
            model_name='task',
            name='current_sy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.schoolyear'),
        ),
    ]
