# Generated by Django 5.0.1 on 2024-01-21 15:56

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.CreateModel(
            name='ChairpersonUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
            managers=[
                ('principle_leader', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
            managers=[
                ('principle_leader', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CHAIRPERSON', 'CHAIRPERSON'), ('MEMBER', 'MEMBER'), ('SBM COORDINATOR', 'SBM COORDINATOR')], default='ADMIN', max_length=30),
        ),
    ]
