# Generated by Django 5.0.1 on 2024-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_normaluser_chairpersonuser_memberuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CHAIRPERSON', 'CHAIRPERSON'), ('MEMBER', 'MEMBER'), ('KPI TEAM', 'KPI TEAM'), ('SBM COORDINATOR', 'SBM COORDINATOR')], default='ADMIN', max_length=30),
        ),
    ]
