# Generated by Django 5.0.1 on 2024-02-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.FileField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
